### ISSUE TITLE
Add / update docker documentation to clean and restart db

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#130]
I am having issues with `docker-compose exec app rake db:setup` when trying to set the database after a test. I am also having problems with `docker-compose exec app rake db:migrate`. 

 A more complete doc on the README will be helpful!

**Comment by viktorsmari** [comment]
Trying to set the db after a test? :thinking: 

If you get errors, please paste the error messages here so I can debug!


Maybe you are experiencing the same thing I have on **many different projects**, is that Postgres denies the connection, but actually finishes the operation before:
```
root@a1268c60d109:/app# rails db:create
Database 'sc_dev' already exists
could not connect to server: No such file or directory
```
Here the db is created but still I get the error
Then I do `rails db:schema:load`

And visit `localhost:3000` and everything is working fine.

**Comment by viktorsmari** [comment]
One issue was caused by `test` database failing to be created because of missing credentials. Rails tries to save you time when doing `db:create` by creating the DEV and TEST db at the same time. If credentials are missing for the TEST, it will create the DEV but error on the TEST db.

That issue has been fixed and the documentation has been updated.
