### ISSUE TITLE
How to get historical readings of today ?

### ISSUE THREAD

**Issue by sergeLabo** [fablabbcn/smartcitizen-api#158]
With the API Get Historical Readings and python request, I can't get
historical readings of today.

If **today is 2020-01-29**,

**today-1 to today**

http://api.smartcitizen.me/v0/devices/9525/readings?sensor_id=113&rollup=1h&from=2020-01-28&to=2020-01-29
return
 {'device_id': 9525, 'sensor_key': 'tvoc', 'sensor_id': 113, 'component_id': 244, 'rollup': '1h', 'function': 'avg', 'from': '2020-01-28T00:00:00Z', 'to': '2020-01-29T00:00:00Z', 'sample_size': 1387,
 'readings': [
             ['2020-01-28T23:00:44Z', 16.1],
             ['2020-01-28T22:00:42Z', 13.6],
             ['2020-01-28T21:00:58Z', 12.8],
                ....
             ['2020-01-28T02:00:21Z', 110.9],
             ['2020-01-28T01:00:04Z', 118.1],
             ['2020-01-28T00:00:57Z', 130.2]
             ]}

**today to today**

http://api.smartcitizen.me/v0/devices/9525/readings?sensor_id=113&rollup=1h&from=2020-01-29&to=2020-01-29
return
{'device_id': 9525, 'sensor_key': 'tvoc', 'sensor_id': 113, 'component_id': 244, 'rollup': '1h', 'function': 'avg', 'from': '2020-01-29T00:00:00Z', 'to': '2020-01-29T00:00:00Z', 'sample_size': 0, 'readings': []}

https://smartcitizen.me/kits/9525 display readings of today. How to get them with the API ?

**Comment by pral2a** [comment]
You need to add the hour and minute range to get an interval within a day

You do this:

https://api.smartcitizen.me/v0/devices/9525/readings?sensor_id=113&rollup=1h&from=2020-01-29%2000:00:00&to=2020-01-29%2012:33:52

Instead of this:

http://api.smartcitizen.me/v0/devices/9525/readings?sensor_id=113&rollup=1h&from=2020-01-29&to=2020-01-29

We recommend ISO 8601 time like, but the previous work

https://api.smartcitizen.me/v0/devices/9525/readings?sensor_id=113&rollup=1h&from=2020-01-29T00:00:00Z&to=2020-01-29T12:33:52Z

Check the documentation for more details

https://developer.smartcitizen.me/#get-historical-readings

**Comment by sergeLabo** [comment]
Thank's, it works! Yes, the documentation is clear!
