### ISSUE TITLE
Cassandra / Kairos connection

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#260]
As we are moving services to different geographical locations, we need to check that the connection between Kairos and Cassandra via SSL is possible.

**Comment by oscgonfer** [comment]
Continues here. Two options to discuss for moving forward:

- Migrate partially (only api) and keep cassandra machine as is (see risk aspect)
- Launch new machine in current datacenter for upgrade of api, and then consider moving both, api and dc over to new location (preferred)

Below some notes in case we opt for a remote connection.

### Connecting Kairos and cassandra remotely

Should we choose to migrate and use remotely between kairos and the datacenter:

#### Kairos configuration

No issues (that I see) in the configuration file for Kairos: https://raw.githubusercontent.com/kairosdb/kairosdb/develop/src/main/resources/kairosdb.conf

#### SSL in Cassandra

I believe this is not enables on our machine: Setting up SSL on cassandra connections
http://docs.datastax.com/en/developer/java-driver/3.1/manual/ssl/

I case we choose to do it in London already, we should consider this.

### Migrating Cassandra Machine

**Migrating from one machine to another**: https://www.linode.com/docs/products/compute/compute-instances/guides/migrate-to-different-dc/

**Possible issues**
> Any existing Backups created through our Linode Backup Service will not be migrated. Once the Compute Instance’s migration has completed, your backup service will restart on its normal schedule.

@pral2a this I believe is quite critical point to consider at this moment of the project. [VLANs](https://www.linode.com/docs/products/networking/vlans/) are datacenter specific.

**Comment by pral2a** [comment]
Here are some suggestions to address the Cassandra topic:

1. My primary suggestion is to follow the Linode migrate to another data centre guide. We could follow some risk management actions such as:

- [Clone](https://www.linode.com/docs/products/compute/compute-instances/guides/clone-instance/) the existing instances to have a backup in case the newly transferred instance has some issues 
- [Download](https://www.linode.com/docs/products/compute/compute-instances/guides/copy-a-disk-image-over-ssh/) a disk image over SSH to have a backup
- Ask @paulormg (our Cassandra expert) to help us backup data and configuration previous to the migration

2. Consider requesting support from @paulormg (our Cassandra expert) to bootstrap the Cassandra machines in the new data centre from the ground up in case we could benefit from a significant upgrade. I will favour this option less because of the complexity it involves.
3. Postpone any migration and keep Cassandra in the existing data center. Consider setting a point-to-point VPN to secure the connection if the SSL option is not feasible. i.e. WireGuard
